### ISSUE TITLE
Ability to specify exactly which middleware to run before or after

### ISSUE THREAD

**Issue by simonw** [simonw/djp#10]
@carltongibson  suggested that middleware be able to say "I should be run directly before/after this other named middleware".

**Comment by simonw** [comment]
Example in this test: https://github.com/simonw/djp/blob/a8d8add2cfcd653a44a68d798ea541dede489d38/tests/plugins/middleware.py#L4-L26

Documentation here: https://djp.readthedocs.io/en/latest/plugin_hooks.html#middleware

**Comment by simonw** [comment]
This took longer than expected because I got stuck on a gnarly bug, which I eventually resolved using OpenAI's `o1-preview`: https://gist.github.com/simonw/03776d9f80534aa8e5348580dc6a800b

**Comment by rptmat57** [comment]
Just a thought, but I am wondering if the item cannot be found if it should throw an error or automatically put the middleware at the beginning/end of the list.
I have a use case where a plugin should be before another plugin if it's installed. if that other plugin is not installed it can be somewhere else. Users don't always have that other plugin installed.

Maybe adding a default position like `nulls_last`, or pass it a flag to not raise an error if it's not found?

I haven't tried it, but maybe I can also implement my conditional ordering logic in the function itself?
```python
@djp.hookimpl
def middleware():
```
